services:
  - type: worker
    name: pump-alert-bot
    env: python
    buildCommand: ""
    startCommand: "bash start.sh"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
